baseURL: http://yufanz.xyz/
languageCode: en-us
title: Yufan Zhang

theme: "PaperMod"

params:
  ShowBreadCrumbs: true
  assets:
    favicon: "logos/head.png"
  profileMode:
    enabled: true
    title: "Yufan Zhang" # optional default will be site title
    first: "Yufan"

    # Positions
    position1_title: "Data Science"
    position1_org: "DKU"
    position2_title: "Creativity Chair"
    position2_org: "SciEcon CIC"

    # imageUrl: "logos/header_logo.png" #"logos/00.jpg" # optional
    imageUrl: "logos/head.png" # optional

    imageTitle: "<title of image as alt>" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size

    image2Url: "logos/Zhang.png"

    profileImageUrl: "logos/test.JPG"
    # buttons:
    #     - name: Archive
    #       url: "/archive"
    #     - name: Github
    #       url: "https://github.com/"

  socialIcons:
    - name: "github"
      url: "https://github.com/iambrucez"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/helloyufan/"
    - name: "twitter"
      url: "https://twitter.com/brucezbrucez"
    - name: "email"
      url: "mailto: yz605@duke.edu"

menu:
  main:
    - name: Project
      url: /project/
      weight: 3
    - name: Blog
      url: /blog/
      weight: 4
    - name: CV
      url: CV.pdf
      weight: 9
    - name: 🔍
      url: search/
      weight: 10
    # - name: Tags
    #   url: tags/
    #   weight: 10
    # - name: Categories
    #   url: categories/
    #   weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
