site_name: Yufan Zhang
theme:
  name: material
  language: en
  # custom_dir: overrides
  font: 
    text: #Roboto Mono #PT Sans #Playfair Display #Raleway #Roboto Slab #Roboto Mono

  palette:
    primary: white
    accent: indigo
  logo: img/logos/logo6.png
  favicon: img/logos/logo8_en.png

  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      pytorch: fontawesome/brands/css3

  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - navigation.tabs.sticky
    
  palette:
    - media: "(prefers-color-scheme: light)" 
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch 
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - 'index.md'
    - '#Bio': 'Home/bio.md'
    - '#Education': 'Home/education.md'
    - '#Skills': 'Home/skills.md'
    - '#Tags': 'Home/tags.md'

  - Projects: 
    - Projects/index.md
    - '#Research':
      - "AlphaFold and GNN": 'Projects/AlphaFold.md'
      - "MF-Net": 'Projects/MFNet.md'
      - "Visualizing NFT Ethics": 'Projects/NFTEthics.md'
    - '#Innovate':
      - "Visualizing DKU's Interdisciplinarity": 'Projects/DKUInterdisciplinarity.md'
      - "Heart Disease Detection Using Machine Learning": 'Projects/HeartDisease.md'
      - "Using CycleGAN for Domain Transfer between MNIST and SVHN": 'Projects/CycleGAN.md'
      - "Evaluating Higher Education Using Machine Learning": 'Projects/HigherEdu.md'
    # - '#Articles':
    #   - 'Development Status and Future Trends of Emerging NFT Market': 'Innovate/DustinAMA.md'
    #   - 'A Glance into Generative Adversarial Network (GAN)': 'Innovate/GAN.md'
    #   - 'NFT Marketplace: How to Choose the Right NFT Marketplace for Artists and Collectors': 'Innovate/NFTartists.md'

  # - Innovate: 
  #   - Innovate/index.md
  #   - '#Projects':
  #     - 'A Glance into NFT Ethics': 'Innovate/CryptoPunkEthics.md'
  #     - "Visualizing DKU's Interdisciplinarity": 'Innovate/DKUInterdisciplinarity.md'
  #     - 'Heart Disease Detection Using Machine Learning': 'Innovate/HeartDisease.md'
  #     - 'Using CycleGAN for Domain Transfer between MNIST and SVHN': 'Innovate/CycleGAN.md'
  #     - 'Evaluating Higher Education Using Machine Learning': 'Innovate/HigherEdu.md'
  #   - '#Articles':
  #     - 'Development Status and Future Trends of Emerging NFT Market': 'Innovate/DustinAMA.md'
  #     - 'A Glance into Generative Adversarial Network (GAN)': 'Innovate/GAN.md'
  #     - 'NFT Marketplace: How to Choose the Right NFT Marketplace for Artists and Collectors': 'Innovate/NFTartists.md'
      
  - Experience: 
    - Experience/index.md
    - 'Institution':
      - 'SciEcon CIC': 'Experience/SciEconCIC.md'
      - 'Duke Kunshan University': 'Experience/DukeKunshan.md'

  - Life:
    - Life/index.md
    - 'Enjoy':
      - 'Shutter Button: The First 10000 Photographs': 'Life/10000Photos.md'
      - 'Graphic Design Portfolio': 'Life/GraphicDesign.md'
    - 'Blog':
      - 'Mac Apps for Productivity': 'Life/MacApps.md'
      - 'What is Wrong with Football in China 中国足球?': 'Life/ChinaFootball.md'
      - 'Involution 内卷: Reflection and Possible Exit Mechanism': 'Life/Involution.md'
      - 'How I Build yufanz.xyz 记录一下建站的过程': 'Life/Build.md'
      - '自我解剖 Info for PS': 'Life/Reflecting.md'
      - 'Graduate Programs': 'Life/GraduatePrograms.md'
  
  - CV: 'CV.pdf'

  # - 'Tags': 'tags.md'

extra:
  social:
    - icon: fontawesome/solid/envelope-open
      link: mailto:<yz605@duke.edu>
      name: Email
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/helloyufan
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/brucezbrucez
    - icon: fontawesome/brands/github
      link: https://github.com/iambrucez

  alternate:
    - name: English
      link: /
      lang: en
    - name: 简体中文
      link: 'zh/Home'
      lang: zh

  # tags:
  #   PyTorch: pytorch
  #   ComputerVision: 'Computer Vision'
  #   HTML: html

plugins:
  - search
  - tags:
      # tags_file: 'Home/Skills.md'
      tags_file: 'Home/tags.md'

copyright: Copyright &copy; 2022 Yufan Zhang

  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX