site_name: Yufan Zhang
theme:
  name: material
  language: en
  # custom_dir: overrides
  font: 
    text: Roboto Mono
  palette:
    primary: white
    accent: indigo
  logo: img/logos/logo6.png
  favicon: img/logos/logo8_en.png

  features:
    - navigation.tabs
    # - toc.integrate
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    # - navigation.tabs.sticky
    

  palette:
    - media: "(prefers-color-scheme: light)" 
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch 
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Home': 
    - 'index.md'
    - '#Bio': 'Home/About.md'
    - '#Education': 'Home/Education.md'
    - '#Skills': 'Home/Skills.md'
  # - 'About': 'About.md'
  - 'Research': 
    - 'Research.md'
    - 'Projects':
      - 'Using AlphaFold and GNN to Predict Catalytic Efficiency': 'Research/AlphaFold.md'
      - 'On Ethics of Ethereum NFT': 'Research/HCIBlockchain.md'
      - 'MF-Net: Few-shot Multilingual Stylized Font Generation': 'Research/MFNet.md'

  - 'Innovate': 
    - 'Innovate.md'
    - 'Projects':
      - 'A Glance into NFT Ethics': 'Innovate/CryptoPunkEthics.md'
      - 'Heart Disease Detection Using Machine Learning': 'Innovate/HeartDisease.md'
      - 'Using CycleGAN for Domain Transfer between MNIST and SVHN': 'Innovate/CycleGAN.md'
    - 'Articles':
      - 'Development Status and Future Trends of Emerging NFT Market': 'Innovate/DustinAMA.md'
      - 'A Glance into Generative Adversarial Network (GAN)': 'Innovate/GAN.md'
      - 'NFT Marketplace: How to Choose the Right NFT Marketplace for Artists and Collectors': 'Innovate/NFTartists.md'
      
  - 'Leadership': 
    # - 'LeadershipService.md'
    - 'SciEcon CIC': 'Leadership/SciEconCIC.md'
    - 'Duke Kunshan University': 'Leadership/DukeKunshan.md'

  - 'Life':
    - 'Life.md'
    - 'Enjoy':
      - 'Shutter Button: The First 10000 Photographs': 'Life/10000Photos.md'
      - 'Graphic Design Portfolio': 'Life/GraphicDesign.md'
    - 'Blog':
      - 'Mac Apps for Productivity': 'Life/MacApps.md'
      - 'What is Wrong with Football in China 中国足球?': 'Life/ChinaFootball.md'
      - 'Involution 内卷: Reflection and Possible Exit Mechanism': 'Life/Involution.md'
      - 'How I Build yufanz.xyz 记录一下建站的过程': 'Life/Build.md'
  
  - 'CV': https://duke.box.com/v/yufanbrucezhang

markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/envelope-open
      link: mailto:<yz605@duke.edu>
      name: Email
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/helloyufan
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/brucezbrucez
    - icon: fontawesome/brands/github
      link: https://github.com/iambrucez

  alternate:
    - name: English
      link: /
      lang: en
    - name: 简体中文
      link: /张宇凡/
      lang: zh

  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX